remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: bmjhayward blog and writings
author: brendan hayward
description: I write about science and technology, mostly. I live in Newcastle Australia and try to enjoy the good moments.
